[project]
name = "poem-prompt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "openai>=1.98.0",
    "requests>=2.32.4",
    "toml>=0.10.2",
]
